@startuml

   :edw.p_cnt_opid();
  :edw.p_fct_detail_scgpwg2();
  split
   :edw.p_rst_finish_frontline();
  split again
   :edw.p_rst_finish_sku();
  split again
   :edw.p_rst_finish_zipper();

  end split
:finish;
@enduml
