@startuml

package "大数据服务器10.10.255.30" {
    database "5432" {
        [postgre]
    }
    database "15432" {
        [gp节点4]
        [gp节点3]
        [gp节点2]
        [gp节点1]
    }
}
note bottom of 15432
greenplum
单机4节点,
分布式列存储,
加快计算速度
end note
package "ERP服务器192.168.2.46" {
    database "1433" {
        [sqlserver]
    }
}
[postgre] <-- [gp节点1]
[postgre] <-- [gp节点2]
[postgre] <-- [gp节点3]
[postgre] <-- [gp节点4]

[gp节点1] <-- [sqlserver]
[gp节点2] <-- [sqlserver]
[gp节点3] <-- [sqlserver]
[gp节点4] <-- [sqlserver]

@enduml
